Code style.

diff --git a/serve b/serve
--- a/serve
+++ b/serve
@@ -7,8 +7,8 @@ INSTALLED=$(php -v | egrep -o -m1 '([0-9]{1,}\.[0-9]{1,}\.[0-9]{1,})')
 OLDER=$(echo -e "$INSTALLED\n$REQUIRED" | sort -V | head -n1)
 
 if [ "$REQUIRED" != "$INSTALLED" ] && [ "$OLDER" == "$INSTALLED" ]; then
- echo " PHP version $REQUIRED is required and $INSTALLED is currently installed."
- exit 1
+    echo " PHP version $REQUIRED is required and $INSTALLED is currently installed."
+    exit 1
 fi
 
 if [ ! -z "$1" ]; then
