Check that correct version of php is installed before trying to start development server.

diff --git a/serve b/serve
--- a/serve
+++ b/serve
@@ -2,6 +2,15 @@
 
 source ./config/config.file
 
+REQUIRED='5.4.0'
+INSTALLED=$(php -v | egrep -o -m1 '([0-9]{1,}\.[0-9]{1,}\.[0-9]{1,})')
+OLDER=$(echo $INSTALLED $REQUIRED | tr " " "\n" | sort -V | head -n 1)
+
+if [ "$REQUIRED" != "$INSTALLED" ] && [ "$OLDER" == "$INSTALLED" ]; then
+ echo " PHP version $REQUIRED is required and $INSTALLED is currently installed"
+ exit 1
+fi
+
 if [ ! -z "$1" ]; then
     PHP_PORT=$1
 elif [ -z "$PHP_PORT" ]; then
